/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/WEGAXeQ0553
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"

export function Cart2() {
  return (
    <div className="fixed top-4 right-4 z-50">
      <Popover>
        <PopoverTrigger asChild>
          <Button className="rounded-full" size="icon" variant="outline">
            <ShoppingCartIcon className="h-6 w-6" />
            <span className="sr-only">Open cart</span>
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-[400px] p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold">Your Cart</h3>
            <span className="text-gray-500 dark:text-gray-400">3 items</span>
          </div>
          <div className="space-y-4">
            <div className="grid grid-cols-[64px_1fr_64px] items-center gap-4">
              <img
                alt="Product image"
                className="rounded-md object-cover"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width={64}
              />
              <div className="space-y-1">
                <p className="font-medium">Acme Hoodie</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">Size: M, Color: Black</p>
              </div>
              <div className="flex items-center justify-end gap-2">
                <span className="font-medium">x2</span>
                <span className="font-medium">$79.99</span>
              </div>
            </div>
            <div className="grid grid-cols-[64px_1fr_64px] items-center gap-4">
              <img
                alt="Product image"
                className="rounded-md object-cover"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width={64}
              />
              <div className="space-y-1">
                <p className="font-medium">Acme T-Shirt</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">Size: L, Color: White</p>
              </div>
              <div className="flex items-center justify-end gap-2">
                <span className="font-medium">x1</span>
                <span className="font-medium">$39.99</span>
              </div>
            </div>
            <div className="grid grid-cols-[64px_1fr_64px] items-center gap-4">
              <img
                alt="Product image"
                className="rounded-md object-cover"
                height={64}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width={64}
              />
              <div className="space-y-1">
                <p className="font-medium">Acme Beanie</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">Color: Navy</p>
              </div>
              <div className="flex items-center justify-end gap-2">
                <span className="font-medium">x1</span>
                <span className="font-medium">$24.99</span>
              </div>
            </div>
          </div>
          <div className="mt-6 flex justify-between">
            <p className="text-gray-500 dark:text-gray-400">Total</p>
            <p className="font-medium">$144.97</p>
          </div>
          <Button className="mt-6 w-full">Checkout</Button>
        </PopoverContent>
      </Popover>
    </div>
  )
}

function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}
